/**
 * The client contract. The React Native apps switch on these values to select a
 * localized message; they never parse `message`.
 */
export const ErrorCodes = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  OPERATOR_NOT_APPROVED: 'OPERATOR_NOT_APPROVED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_REPLAYED: 'REFRESH_TOKEN_REPLAYED',
  SETUP_TOKEN_INVALID: 'SETUP_TOKEN_INVALID',
  OTP_INVALID: 'OTP_INVALID',
  RATE_LIMITED: 'RATE_LIMITED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  OPERATOR_NOT_FOUND: 'OPERATOR_NOT_FOUND',
  PHONE_COUNTRY_UNSUPPORTED: 'PHONE_COUNTRY_UNSUPPORTED',
  SMS_DELIVERY_FAILED: 'SMS_DELIVERY_FAILED',

  LOCATION_NOT_FOUND: 'LOCATION_NOT_FOUND',
  SESSION_TYPE_NOT_FOUND: 'SESSION_TYPE_NOT_FOUND',
  NOT_AT_LOCATION: 'NOT_AT_LOCATION',
  WINDOW_CROSSES_BUSINESS_DAY: 'WINDOW_CROSSES_BUSINESS_DAY',
  CHECKIN_TICK_CONFLICT: 'CHECKIN_TICK_CONFLICT',
  CHECKIN_NOT_FOUND: 'CHECKIN_NOT_FOUND',
  BREAK_HAS_BOOKINGS: 'BREAK_HAS_BOOKINGS',

  SLOT_UNAVAILABLE: 'SLOT_UNAVAILABLE',
  BOOKING_NOT_FOUND: 'BOOKING_NOT_FOUND',
  CUSTOMER_ALREADY_BOOKED: 'CUSTOMER_ALREADY_BOOKED',
  PHONE_NOT_VERIFIED: 'PHONE_NOT_VERIFIED',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  ACTOR_NOT_PERMITTED: 'ACTOR_NOT_PERMITTED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
