/**
 * The client contract. The React Native apps switch on these values to select a
 * localized message; they never parse `message`.
 */
export const ErrorCodes = {
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  OPERATOR_NOT_APPROVED: 'OPERATOR_NOT_APPROVED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  REFRESH_TOKEN_REPLAYED: 'REFRESH_TOKEN_REPLAYED',
  SETUP_TOKEN_INVALID: 'SETUP_TOKEN_INVALID',
  OTP_INVALID: 'OTP_INVALID',
  RATE_LIMITED: 'RATE_LIMITED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  OPERATOR_NOT_FOUND: 'OPERATOR_NOT_FOUND',
  PHONE_COUNTRY_UNSUPPORTED: 'PHONE_COUNTRY_UNSUPPORTED',
  SMS_DELIVERY_FAILED: 'SMS_DELIVERY_FAILED',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
